# ######## Window rules ########

windowrule {
    name = disable-blur-xwayland
    match:class = ^()$
    match:title = ^()$
    no_blur = on
}

windowrule {
    name = disable-blur-xwayland-2
    match:xwayland = 1
    no_blur = on
}

# Floating dialogs
windowrule {
    name = open-file-dialog
    match:title = ^(Open File)(.*)$
    float = on
    center = on
}

windowrule {
    name = select-file-dialog
    match:title = ^(Select a File)(.*)$
    float = on
    center = on
}

windowrule {
    name = choose-wallpaper
    match:title = ^(Choose wallpaper)(.*)$
    float = on
    center = on
    size = 60% 65%
}

windowrule {
    name = open-folder
    match:title = ^(Open Folder)(.*)$
    float = on
    center = on
}

windowrule {
    name = save-as
    match:title = ^(Save As)(.*)$
    float = on
    center = on
}

windowrule {
    name = library
    match:title = ^(Library)(.*)$
    float = on
    center = on
}

windowrule {
    name = file-upload
    match:title = ^(File Upload)(.*)$
    float = on
    center = on
}

windowrule {
    name = wants-to-save
    match:title = ^(.*)(wants to save)$
    float = on
    center = on
}

windowrule {
    name = wants-to-open
    match:title = ^(.*)(wants to open)$
    float = on
    center = on
}

# Specific apps
windowrule {
    name = blueberry
    match:class = ^blueberry\.py$
    float = on
}

windowrule {
    name = guifetch
    match:class = ^guifetch$
    float = on
}

windowrule {
    name = pavucontrol
    match:class = ^pavucontrol$
    float = on
    size = 45%
    center = on
}

windowrule {
    name = pavucontrol-kde
    match:class = ^org\.pulseaudio\.pavucontrol$
    float = on
    size = 45%
    center = on
}

windowrule {
    name = nm-connection-editor
    match:class = ^nm-connection-editor$
    float = on
    size = 45%
    center = on
}

windowrule {
    name = zotero
    match:class = ^Zotero$
    float = on
    size = 45%
}

# Tiling
windowrule {
    name = warp-tile
    match:class = ^dev\.warp\.Warp$
    tile = on
}

# Picture-in-Picture
windowrule {
    name = pip
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = on
    keep_aspect_ratio = on
    pin = on
    move = 73% 72%
    size = 25%
}

# Tearing
windowrule {
    name = allow-tearing-exe
    match:title = .*\.exe
    immediate = on
}

windowrule {
    name = allow-tearing-minecraft
    match:title = .*minecraft.*
    immediate = on
}

windowrule {
    name = allow-tearing-steam
    match:class = ^steam_app.*
    immediate = on
}

